- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - qemu-kvm
    - libvirt-daemon-system
    - libvirt-clients
    - bridge-utils
    - virtinst
    - virt-manager
    - libguestfs-tools
    - virt-top
    - ovmf
  become: true
  tags: virtualization_prereq
  