- name: Load the overlay and bridge filter filter modules
  become: yes
  ansible.builtin.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter
  when: ansible_os_family == "RedHat"

- name: Add required sysctl parameters and persist
  become: yes
  ansible.builtin.copy:
    dest: "/etc/sysctl.d/k8s.conf"
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
  when: ansible_os_family == "RedHat"

- name: Apply sysctl parameters without a reboot
  become: yes
  ansible.builtin.command: sysctl --system
  when: ansible_os_family == "RedHat"