- name: Add Kubernetes repository on RedHat-based Linux
  become: yes
  ansible.builtin.yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://pkgs.k8s.io/core:/stable:/v1.34/rpm/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://pkgs.k8s.io/core:/stable:/v1.34/rpm/repodata/repomd.xml.key
    state: present
    exclude: kubelet kubeadm kubectl cri-tools kubernetes-cni
  when: ansible_os_family == "RedHat"

- name: Update all packages to the latest version
  become: yes
  ansible.builtin.package:
    name:   "*"
    state:  latest