- name: Disable swap immediately
  ansible.builtin.command: swapoff -a
  become: yes

- name: Comment out swap entries in /etc/fstab to disable swap permanently
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*\s+swap\s+)'
    replace: '# \1'
  become: yes

- name: Remove ZRAM on Fedora
  become: yes
  ansible.builtin.package:
    name:   zram-generator-defaults
    state:  absent
  #when: ansible_distribution == "Fedora"