  - name: Install kubeadm, kubelet and kubectl
    become: yes
    dnf:
      name: "{{ item }}"
      state: present
      disable_excludes: kubernetes
    loop:
      - kubeadm
      - kubelet
      - kubectl
      - cri-tools
    when: ansible_os_family == "RedHat"

  - name: Enable kubelet on RedHat-based Linux
    become: yes
    service:
      name:    kubelet
      state:   started
      enabled: yes
    when: ansible_os_family == "RedHat"