---
- hosts:    localhost
  gather_facts: true

  tasks:

  
  # - name: Install kubeadm, kubelet, and kubectl
  #   package:
  #     name: "{{ item }}"
  #     state: present
  #   loop:
  #     - kubernetes1.33-kubeadm-1.33.3-1.fc42.x86_64 # kubeadm
  #     - kubernetes1.33-1.33.3-1.fc42.x86_64         # kubelet
  #     - kubernetes1.33-client-1.33.3-1.fc42.x86_64  # kubectl
  
  # - name: Enable kubelet on RedHat-based Linux
  #   service:
  #     name:    kubelet
  #     state:   started
  #     enabled: yes
  #   when: ansible_os_family == "RedHat"

  # - name: Initialize Kubernetes master
  #   command: "kubeadm init --pod-network-cidr=10.10.0.0/16"
  #   register: kubeadm_output
  #   ignore_errors: yes

  # - name: Create the .kube directory
  #   file:
  #     path: /home/quintellarosa/.kube
  #     state: directory

  # - name: Copy Kubernetes config file to the current user
  #   copy:
  #     remote_src: true
  #     src: /etc/kubernetes/admin.conf 
  #     dest: /home/quintellarosa/.kube/config
  #     owner: quintellarosa
  #     group: quintellarosa

  # - name: Allow the control plane to also run pods for applications
  #   command: "kubectl taint nodes --all node-role.kubernetes.io/control-plane:NoSchedule-"
  #   become: yes
  #   become_user: quintellarosa
  #   ignore_errors: yes

  # - name: Deploy the Calico operator
  #   command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/tigera-operator.yaml
  # #   when: "'calico' in kubeadm_output.stdout"

  # - name: Download Calico’s custom-resources file 
  #   command: curl https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/custom-resources.yaml -O

  # - name: Update the CIDR defined in the custom-resources file to match the pod's network.
  #   replace:
  #     path: ./custom-resources.yaml
  #     regexp: '(\s+)cidr: 192\.168\.0\.0\/16/(\s+.*)?$'
  #     replace: '\1cidr: 10.10.0.0\/16\2'

  # - name: Create resources defined in the Calico custom resource YAML file.
  #   command: kubectl create -f custom-resources.yaml

  # - name: Download rancher.io/local-path storage class
  #   command: kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml

  # - name: Make this storage class (local-path) the default
  #   command: "kubectl patch storageclass local-path -p '{\"metadata\": {\"annotations\":{\"storageclass.kubernetes.io/is-default-class\":\"true\"}}}'"
