- name: Install required packages
  become: true
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - libvirt-daemon-driver-network
    - libvirt-daemon-driver-nodedev
    - libvirt-daemon-driver-qemu
    - libvirt-daemon-driver-storage-core
    - qemu-audio-spice
    - qemu-char-spice
    - qemu-device-display-qxl
    - qemu-device-display-virtio-gpu
    - qemu-device-display-virtio-vga
    - qemu-device-usb-redirect
    - qemu-system-x86-core

#     sudo systemctl --now enable virtnetworkd.service
# sudo systemctl --now enable virtqemud.service
  